[package]
name = "hyprland_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

itertools = "0.10.5"
smart-default = "0.6.0"

eyre = "0.6.8"